### ISSUE TITLE
java errors

### ISSUE THREAD

**Issue by dfamil** [memoakten/max-skeletonML#1]
hi  

i am getting java errros when i run Kinect2Receiver it MaxMsp 7 

```
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
at com.cycling74.max.MXJClassLoaderImpl.doLoadClass(MXJClassLoaderImpl.java:117)
at com.cycling74.max.MXJClassLoader.loadClazz(MXJClassLoader.java:88)
```

Could not load class 'Kinect2Receiver'

**Comment by dfamil** [comment]
hi
recomplied it in java 6 works now mac seems to only like java 6 in some cases

**Comment by memoakten** [comment]
Hi, yea sorry about that. I still haven't figured out exactly what Max's deal is with Java. Seems you do need an older version I think.
